site_name: tianliangtian's pages
site_url: https://tianliangtian.github.io
site_author: tianliangtian

theme:
  name: material
  icon: 
    logo: material/library
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: pink
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: pink
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Learning: 
    - Learning/index.md
    - Python: Learning/Python.md
    - Deep Learning:
      - Neural Network and Deep Learning: Learning/DeepLearning/NNandDL.md
      - Transformer: Learning/DeepLearning/Transformer.md
    - Computer Vision:
      - ML4360 - Computer vision: Learning/CV/ML.md
      - 4DGS: Learning/CV/4DGS.md
    - DL4CV:
      - Classifier: Learning/DL4CV/Classifier.md
      - Neural Network: Learning/DL4CV/NN.md
      - CNN: Learning/DL4CV/CNN.md
      - Training: Learning/DL4CV/Training.md
      - Object Detection: Learning/DL4CV/OD.md
      - Semantic Segmentation: Learning/DL4CV/SS.md
    - GAMES101:
      - Introduction: Learning/GAMES101/GAMES101.md
      - Rasterization: Learning/GAMES101/Rasterization.md
      - Shading: Learning/GAMES101/Shading.md
      - Geometry: Learning/GAMES101/Geometry.md
      - Ray Tracing: Learning/GAMES101/RayTracing.md
    - Miscellaneous: Learning/Miscellaneous.md
  - Tools:
    - Tools/index.md
    - Git: Tools/Git.md
    - Website building: Tools/Website-building.md
    - Anaconda: Tools/Anaconda.md
    - Python: Tools/Python.md
    - Linux: 
      - Tools/Linux/tmux.md
plugins:
  - search
  - tags
  - glightbox
extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://b23.tv/HokHR7N
    - icon: fontawesome/brands/github
      link: https://github.com/tianliangtian
  homepage: https://tianliangtian.github.io

markdown_extensions:
  - pymdownx.arithmatex:            # mathjax
      generic: true
  - pymdownx.highlight:             # syntax highlight
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:                # Content tabs
      alternate_style: true
  - tables                          # table
  - def_list                        # lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list                       # image
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

